### ISSUE TITLE
求助一下跑不起来，不过有点看不太懂 分别是运行session.py 跟 do.py报的错

### ISSUE THREAD

**Issue by qq985382384** [Rominwolf/dokta-office-mirai#1]
![image](https://user-images.githubusercontent.com/53076564/106020341-9c967d80-60fe-11eb-8619-766bda213c62.png)

![image](https://user-images.githubusercontent.com/53076564/106020286-90122500-60fe-11eb-84c3-58449cdf6a2a.png)

**Comment by Rominwolf** [comment]
您好，请问这些文件都放在同一目录下了吗？

**Comment by qq985382384** [comment]
指的是整个项目的文件吗？我是直接clone下来的

**Comment by qq985382384** [comment]
我的环境是3.6.5

**Comment by Rominwolf** [comment]
> 指的是整个项目的文件吗？我是直接clone下来的

啊……那可有点儿麻烦了……
请问是已经成功运行mirai和其mirai-http-api应用并配置好了authKey等必须配置的参数了吗？

**Comment by qq985382384** [comment]
对了我用的是mirai-console-loader
![image](https://user-images.githubusercontent.com/53076564/106154153-47b83d00-61ba-11eb-87e7-1755ea81fecd.png)
 mirai-http-api也能跑起来

**Comment by Rominwolf** [comment]
嗯…… 那 MiraiHttpApi.py 文件中的 host、authKey 和 qq 变量都修改成 mirai-http-api 中设定的信息了吗？

**Comment by qq985382384** [comment]
对的 都改了

**Comment by Rominwolf** [comment]
那请问 DoVars.py 文件中的 configFolder 变量值改成您运行 mirai 的文件夹/config/DoktaOffice/ 了吗？（如果没有 DoktaOffice 这个文件夹需要创建其文件夹）

**Comment by qq985382384** [comment]
这个吗 我建在mirai-console-loader的config下了 不清楚对不对![image](https://user-images.githubusercontent.com/53076564/106168411-33c80780-61c9-11eb-876f-80450b503b02.png)

**Comment by Rominwolf** [comment]
嗯，是的

**Comment by qq985382384** [comment]
问一下大佬的python是什么版本 也有可能是我环境问题，这里问问题太不方便了顺带求个QQ
![image](https://user-images.githubusercontent.com/53076564/106170074-1005c100-61cb-11eb-84ad-58116de91fad.png)

**Comment by Rominwolf** [comment]
啊啊，我用的python版本是3.6.8……
确实，我的QQ是657442693

**Comment by Rominwolf** [comment]
问题解决：请安装 Python 的 configparser 库。
